"""Country reference data used by the Phase 3 query-understanding layer.

The tables below are generated from the same Natural Earth world map that the
frontend globe renders (``frontend/public/world.geojson``), so the assistant
recognises the same country names, ISO codes, and continents the map uses.
The hand-maintained ``COUNTRY_ALIASES_EXTRA`` entry adds the short forms that
news reporting commonly uses.
"""

COUNTRY_NAMES: dict[str, str] = {
    "AE": "United Arab Emirates",
    "AF": "Afghanistan",
    "AL": "Albania",
    "AM": "Armenia",
    "AO": "Angola",
    "AQ": "Antarctica",
    "AR": "Argentina",
    "AT": "Austria",
    "AU": "Australia",
    "AZ": "Azerbaijan",
    "BA": "Bosnia and Herz.",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "BI": "Burundi",
    "BJ": "Benin",
    "BN": "Brunei",
    "BO": "Bolivia",
    "BR": "Brazil",
    "BS": "Bahamas",
    "BT": "Bhutan",
    "BW": "Botswana",
    "BY": "Belarus",
    "BZ": "Belize",
    "CA": "Canada",
    "CD": "Dem. Rep. Congo",
    "CF": "Central African Rep.",
    "CG": "Congo",
    "CH": "Switzerland",
    "CI": "C\u00f4te d'Ivoire",
    "CL": "Chile",
    "CM": "Cameroon",
    "CN": "N. Cyprus",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": "Czechia",
    "DE": "Germany",
    "DJ": "Djibouti",
    "DK": "Denmark",
    "DO": "Dominican Rep.",
    "DZ": "Algeria",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    "EH": "W. Sahara",
    "ER": "Eritrea",
    "ES": "Spain",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FJ": "Fiji",
    "FK": "Falkland Is.",
    "GA": "Gabon",
    "GB": "United Kingdom",
    "GE": "Georgia",
    "GH": "Ghana",
    "GL": "Greenland",
    "GM": "Gambia",
    "GN": "Guinea",
    "GQ": "Eq. Guinea",
    "GR": "Greece",
    "GT": "Guatemala",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HN": "Honduras",
    "HR": "Croatia",
    "HT": "Haiti",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IN": "India",
    "IQ": "Iraq",
    "IR": "Iran",
    "IS": "Iceland",
    "IT": "Italy",
    "JM": "Jamaica",
    "JO": "Jordan",
    "JP": "Japan",
    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "KH": "Cambodia",
    "KO": "Kosovo",
    "KP": "North Korea",
    "KR": "South Korea",
    "KW": "Kuwait",
    "KZ": "Kazakhstan",
    "LA": "Laos",
    "LB": "Lebanon",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "LY": "Libya",
    "MA": "Morocco",
    "MD": "Moldova",
    "ME": "Montenegro",
    "MG": "Madagascar",
    "MK": "North Macedonia",
    "ML": "Mali",
    "MM": "Myanmar",
    "MN": "Mongolia",
    "MR": "Mauritania",
    "MW": "Malawi",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NC": "New Caledonia",
    "NE": "Niger",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Netherlands",
    "NP": "Nepal",
    "NZ": "New Zealand",
    "OM": "Oman",
    "PA": "Panama",
    "PE": "Peru",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PR": "Puerto Rico",
    "PS": "Palestine",
    "PT": "Portugal",
    "PY": "Paraguay",
    "QA": "Qatar",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russia",
    "RW": "Rwanda",
    "SA": "Saudi Arabia",
    "SB": "Solomon Is.",
    "SD": "Sudan",
    "SE": "Sweden",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "SL": "Somaliland",
    "SN": "Senegal",
    "SO": "Somalia",
    "SR": "Suriname",
    "SS": "S. Sudan",
    "SV": "El Salvador",
    "SY": "Syria",
    "SZ": "eSwatini",
    "TD": "Chad",
    "TF": "Fr. S. Antarctic Lands",
    "TG": "Togo",
    "TH": "Thailand",
    "TJ": "Tajikistan",
    "TL": "Timor-Leste",
    "TM": "Turkmenistan",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TT": "Trinidad and Tobago",
    "TW": "Taiwan",
    "TZ": "Tanzania",
    "UA": "Ukraine",
    "UG": "Uganda",
    "US": "United States of America",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "VU": "Vanuatu",
    "YE": "Yemen",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
}

COUNTRY_CONTINENTS: dict[str, str] = {
    "AE": "Asia",
    "AF": "Asia",
    "AL": "Europe",
    "AM": "Asia",
    "AO": "Africa",
    "AQ": "Antarctica",
    "AR": "South America",
    "AT": "Europe",
    "AU": "Oceania",
    "AZ": "Asia",
    "BA": "Europe",
    "BD": "Asia",
    "BE": "Europe",
    "BF": "Africa",
    "BG": "Europe",
    "BI": "Africa",
    "BJ": "Africa",
    "BN": "Asia",
    "BO": "South America",
    "BR": "South America",
    "BS": "North America",
    "BT": "Asia",
    "BW": "Africa",
    "BY": "Europe",
    "BZ": "North America",
    "CA": "North America",
    "CD": "Africa",
    "CF": "Africa",
    "CG": "Africa",
    "CH": "Europe",
    "CI": "Africa",
    "CL": "South America",
    "CM": "Africa",
    "CN": "Asia",
    "CO": "South America",
    "CR": "North America",
    "CU": "North America",
    "CY": "Asia",
    "CZ": "Europe",
    "DE": "Europe",
    "DJ": "Africa",
    "DK": "Europe",
    "DO": "North America",
    "DZ": "Africa",
    "EC": "South America",
    "EE": "Europe",
    "EG": "Africa",
    "EH": "Africa",
    "ER": "Africa",
    "ES": "Europe",
    "ET": "Africa",
    "FI": "Europe",
    "FJ": "Oceania",
    "FK": "South America",
    "GA": "Africa",
    "GB": "Europe",
    "GE": "Asia",
    "GH": "Africa",
    "GL": "North America",
    "GM": "Africa",
    "GN": "Africa",
    "GQ": "Africa",
    "GR": "Europe",
    "GT": "North America",
    "GW": "Africa",
    "GY": "South America",
    "HN": "North America",
    "HR": "Europe",
    "HT": "North America",
    "HU": "Europe",
    "ID": "Asia",
    "IE": "Europe",
    "IL": "Asia",
    "IN": "Asia",
    "IQ": "Asia",
    "IR": "Asia",
    "IS": "Europe",
    "IT": "Europe",
    "JM": "North America",
    "JO": "Asia",
    "JP": "Asia",
    "KE": "Africa",
    "KG": "Asia",
    "KH": "Asia",
    "KO": "Europe",
    "KP": "Asia",
    "KR": "Asia",
    "KW": "Asia",
    "KZ": "Asia",
    "LA": "Asia",
    "LB": "Asia",
    "LK": "Asia",
    "LR": "Africa",
    "LS": "Africa",
    "LT": "Europe",
    "LU": "Europe",
    "LV": "Europe",
    "LY": "Africa",
    "MA": "Africa",
    "MD": "Europe",
    "ME": "Europe",
    "MG": "Africa",
    "MK": "Europe",
    "ML": "Africa",
    "MM": "Asia",
    "MN": "Asia",
    "MR": "Africa",
    "MW": "Africa",
    "MX": "North America",
    "MY": "Asia",
    "MZ": "Africa",
    "NA": "Africa",
    "NC": "Oceania",
    "NE": "Africa",
    "NG": "Africa",
    "NI": "North America",
    "NL": "Europe",
    "NP": "Asia",
    "NZ": "Oceania",
    "OM": "Asia",
    "PA": "North America",
    "PE": "South America",
    "PG": "Oceania",
    "PH": "Asia",
    "PK": "Asia",
    "PL": "Europe",
    "PR": "North America",
    "PS": "Asia",
    "PT": "Europe",
    "PY": "South America",
    "QA": "Asia",
    "RO": "Europe",
    "RS": "Europe",
    "RU": "Europe",
    "RW": "Africa",
    "SA": "Asia",
    "SB": "Oceania",
    "SD": "Africa",
    "SE": "Europe",
    "SI": "Europe",
    "SK": "Europe",
    "SL": "Africa",
    "SN": "Africa",
    "SO": "Africa",
    "SR": "South America",
    "SS": "Africa",
    "SV": "North America",
    "SY": "Asia",
    "SZ": "Africa",
    "TD": "Africa",
    "TF": "Seven seas (open ocean)",
    "TG": "Africa",
    "TH": "Asia",
    "TJ": "Asia",
    "TL": "Asia",
    "TM": "Asia",
    "TN": "Africa",
    "TR": "Asia",
    "TT": "North America",
    "TW": "Asia",
    "TZ": "Africa",
    "UA": "Europe",
    "UG": "Africa",
    "US": "North America",
    "UY": "South America",
    "UZ": "Asia",
    "VE": "South America",
    "VN": "Asia",
    "VU": "Oceania",
    "YE": "Asia",
    "ZA": "Africa",
    "ZM": "Africa",
    "ZW": "Africa",
}

COUNTRY_ALIASES: dict[str, str] = {
    "afg.": "AF",
    "afghanistan": "AF",
    "alb.": "AL",
    "albania": "AL",
    "alg.": "DZ",
    "algeria": "DZ",
    "america": "US",
    "ang.": "AO",
    "angola": "AO",
    "ant.": "AQ",
    "antarctica": "AQ",
    "arab republic of egypt": "EG",
    "arg.": "AR",
    "argentina": "AR",
    "argentine republic": "AR",
    "arm.": "AM",
    "armenia": "AM",
    "aust.": "AT",
    "australia": "AU",
    "austria": "AT",
    "auz.": "AU",
    "aze.": "AZ",
    "azerbaijan": "AZ",
    "b.f.": "BF",
    "b.h.": "BA",
    "bahamas": "BS",
    "bahamas, the": "BS",
    "bang.": "BD",
    "bangladesh": "BD",
    "bela.": "BY",
    "belarus": "BY",
    "belg.": "BE",
    "belgium": "BE",
    "belize": "BZ",
    "benin": "BJ",
    "bhs.": "BS",
    "bhutan": "BT",
    "bolivarian republic of venezuela": "VE",
    "bolivia": "BO",
    "bosnia and herz.": "BA",
    "bosnia and herzegovina": "BA",
    "botswana": "BW",
    "brazil": "BR",
    "brunei": "BN",
    "brunei darussalam": "BN",
    "bulg.": "BG",
    "bulgaria": "BG",
    "bur.": "BI",
    "burkina faso": "BF",
    "burma": "MM",
    "burundi": "BI",
    "bwa.": "BW",
    "c.a.r.": "CF",
    "c.r.": "CR",
    "cam.": "CM",
    "camb.": "KH",
    "cambodia": "KH",
    "cameroon": "CM",
    "can.": "CA",
    "canada": "CA",
    "central african rep.": "CF",
    "central african republic": "CF",
    "chad": "TD",
    "chile": "CL",
    "china": "CN",
    "co-operative republic of guyana": "GY",
    "col.": "CO",
    "colombia": "CO",
    "commonwealth of australia": "AU",
    "commonwealth of puerto rico": "PR",
    "commonwealth of the bahamas": "BS",
    "congo": "CG",
    "congo, democratic republic of the": "CD",
    "congo, republic of the": "CG",
    "costa rica": "CR",
    "cote d'ivoire": "CI",
    "cro.": "HR",
    "croatia": "HR",
    "cuba": "CU",
    "cyp.": "CY",
    "cyprus": "CY",
    "cz.": "CZ",
    "czech republic": "CZ",
    "czechia": "CZ",
    "c\u00f4te d'ivoire": "CI",
    "d.r.c.": "CD",
    "dem. rep. congo": "CD",
    "dem. rep. korea": "KP",
    "democratic people's republic of korea": "KP",
    "democratic republic of the congo": "CD",
    "democratic republic of timor-leste": "TL",
    "democratic socialist republic of sri lanka": "LK",
    "den.": "DK",
    "denmark": "DK",
    "dji.": "DJ",
    "djibouti": "DJ",
    "dom. rep.": "DO",
    "dominican rep.": "DO",
    "dominican republic": "DO",
    "east timor": "TL",
    "ecu.": "EC",
    "ecuador": "EC",
    "egypt": "EG",
    "el salvador": "SV",
    "el. s.": "SV",
    "eq. g.": "GQ",
    "eq. guinea": "GQ",
    "equatorial guinea": "GQ",
    "erit.": "ER",
    "eritrea": "ER",
    "est.": "EE",
    "estonia": "EE",
    "esw.": "SZ",
    "eswatini": "SZ",
    "eth.": "ET",
    "ethiopia": "ET",
    "falkland is.": "FK",
    "falkland islands": "FK",
    "falkland islands (islas malvinas)": "FK",
    "falkland islands / malvinas": "FK",
    "federal democratic republic of ethiopia": "ET",
    "federal republic of germany": "DE",
    "federal republic of nigeria": "NG",
    "federal republic of somalia": "SO",
    "federative republic of brazil": "BR",
    "fiji": "FJ",
    "fin.": "FI",
    "finland": "FI",
    "flk. is.": "FK",
    "fr. s. and antarctic lands": "TF",
    "fr. s. antarctic lands": "TF",
    "fr. s.a.l.": "TF",
    "french southern and antarctic lands": "TF",
    "gabon": "GA",
    "gabonese republic": "GA",
    "gambia": "GM",
    "gambia, the": "GM",
    "geo.": "GE",
    "georgia": "GE",
    "ger.": "DE",
    "germany": "DE",
    "ghana": "GH",
    "gin.": "GN",
    "gnb.": "GW",
    "grand duchy of luxembourg": "LU",
    "great britain and northern ireland": "GB",
    "greece": "GR",
    "greenland": "GL",
    "grlnd.": "GL",
    "guat.": "GT",
    "guatemala": "GT",
    "guinea": "GN",
    "guinea-bissau": "GW",
    "guy.": "GY",
    "guyana": "GY",
    "haiti": "HT",
    "hashemite kingdom of jordan": "JO",
    "hellenic republic": "GR",
    "hond.": "HN",
    "honduras": "HN",
    "hun.": "HU",
    "hungary": "HU",
    "i.c.": "CI",
    "iceland": "IS",
    "independent state of papua new guinea": "PG",
    "india": "IN",
    "indo.": "ID",
    "indonesia": "ID",
    "iran": "IR",
    "iraq": "IQ",
    "ire.": "IE",
    "ireland": "IE",
    "islamic republic of iran": "IR",
    "islamic republic of mauritania": "MR",
    "islamic republic of pakistan": "PK",
    "islamic state of afghanistan": "AF",
    "islas malvinas": "FK",
    "isr.": "IL",
    "israel": "IL",
    "italian republic": "IT",
    "italy": "IT",
    "ivory coast": "CI",
    "jam.": "JM",
    "jamaica": "JM",
    "japan": "JP",
    "jord.": "JO",
    "jordan": "JO",
    "kaz.": "KZ",
    "kazakhstan": "KZ",
    "ken.": "KE",
    "kenya": "KE",
    "kgz.": "KG",
    "kingdom of belgium": "BE",
    "kingdom of bhutan": "BT",
    "kingdom of cambodia": "KH",
    "kingdom of denmark": "DK",
    "kingdom of eswatini": "SZ",
    "kingdom of lesotho": "LS",
    "kingdom of morocco": "MA",
    "kingdom of saudi arabia": "SA",
    "kingdom of spain": "ES",
    "kingdom of sweden": "SE",
    "kingdom of thailand": "TH",
    "kingdom of the netherlands": "NL",
    "korea": "KP",
    "korea, north": "KP",
    "korea, south": "KR",
    "kos.": "KO",
    "kosovo": "KO",
    "kuwait": "KW",
    "kwt.": "KW",
    "kyrgyz republic": "KG",
    "kyrgyzstan": "KG",
    "lao pdr": "LA",
    "lao people's democratic republic": "LA",
    "laos": "LA",
    "lat.": "LV",
    "latvia": "LV",
    "leb.": "LB",
    "lebanese republic": "LB",
    "lebanon": "LB",
    "les.": "LS",
    "lesotho": "LS",
    "liberia": "LR",
    "libya": "LY",
    "lith.": "LT",
    "lithuania": "LT",
    "lux.": "LU",
    "luxembourg": "LU",
    "mad.": "MG",
    "madagascar": "MG",
    "mal.": "MW",
    "malawi": "MW",
    "malay.": "MY",
    "malaysia": "MY",
    "mali": "ML",
    "mauritania": "MR",
    "mda.": "MD",
    "mex.": "MX",
    "mexico": "MX",
    "moldova": "MD",
    "mong.": "MN",
    "mongolia": "MN",
    "mont.": "ME",
    "montenegro": "ME",
    "mor.": "MA",
    "morocco": "MA",
    "moz.": "MZ",
    "mozambique": "MZ",
    "mrt.": "MR",
    "myan.": "MM",
    "myanmar": "MM",
    "n. cy.": "CN",
    "n. cyprus": "CN",
    "n. mac.": "MK",
    "n.k.": "KP",
    "n.z.": "NZ",
    "nam.": "NA",
    "namibia": "NA",
    "negara brunei darussalam": "BN",
    "nepal": "NP",
    "neth.": "NL",
    "netherlands": "NL",
    "new c.": "NC",
    "new caledonia": "NC",
    "new zealand": "NZ",
    "nic.": "NI",
    "nicaragua": "NI",
    "niger": "NE",
    "nigeria": "NG",
    "north korea": "KP",
    "north macedonia": "MK",
    "northern cyprus": "CN",
    "oman": "OM",
    "oriental republic of uruguay": "UY",
    "p.n.g.": "PG",
    "p.r.": "PR",
    "pak.": "PK",
    "pakistan": "PK",
    "pal.": "PS",
    "palestine": "PS",
    "pan.": "PA",
    "panama": "PA",
    "papua new guinea": "PG",
    "para.": "PY",
    "paraguay": "PY",
    "people's democratic republic of algeria": "DZ",
    "people's republic of angola": "AO",
    "people's republic of bangladesh": "BD",
    "people's republic of china": "CN",
    "peru": "PE",
    "phil.": "PH",
    "philippines": "PH",
    "plurinational state of bolivia": "BO",
    "pol.": "PL",
    "poland": "PL",
    "port.": "PT",
    "portugal": "PT",
    "portuguese republic": "PT",
    "puerto rico": "PR",
    "qatar": "QA",
    "rep. congo": "CG",
    "republic of albania": "AL",
    "republic of armenia": "AM",
    "republic of austria": "AT",
    "republic of azerbaijan": "AZ",
    "republic of belarus": "BY",
    "republic of benin": "BJ",
    "republic of botswana": "BW",
    "republic of bulgaria": "BG",
    "republic of burundi": "BI",
    "republic of cameroon": "CM",
    "republic of chad": "TD",
    "republic of chile": "CL",
    "republic of colombia": "CO",
    "republic of costa rica": "CR",
    "republic of croatia": "HR",
    "republic of cuba": "CU",
    "republic of cyprus": "CY",
    "republic of djibouti": "DJ",
    "republic of ecuador": "EC",
    "republic of el salvador": "SV",
    "republic of equatorial guinea": "GQ",
    "republic of estonia": "EE",
    "republic of fiji": "FJ",
    "republic of finland": "FI",
    "republic of ghana": "GH",
    "republic of guatemala": "GT",
    "republic of guinea": "GN",
    "republic of guinea-bissau": "GW",
    "republic of haiti": "HT",
    "republic of honduras": "HN",
    "republic of hungary": "HU",
    "republic of iceland": "IS",
    "republic of india": "IN",
    "republic of indonesia": "ID",
    "republic of iraq": "IQ",
    "republic of ivory coast": "CI",
    "republic of kazakhstan": "KZ",
    "republic of kenya": "KE",
    "republic of korea": "KR",
    "republic of kosovo": "KO",
    "republic of latvia": "LV",
    "republic of liberia": "LR",
    "republic of lithuania": "LT",
    "republic of madagascar": "MG",
    "republic of malawi": "MW",
    "republic of mali": "ML",
    "republic of moldova": "MD",
    "republic of mozambique": "MZ",
    "republic of namibia": "NA",
    "republic of nicaragua": "NI",
    "republic of niger": "NE",
    "republic of north macedonia": "MK",
    "republic of panama": "PA",
    "republic of paraguay": "PY",
    "republic of peru": "PE",
    "republic of poland": "PL",
    "republic of rwanda": "RW",
    "republic of senegal": "SN",
    "republic of serbia": "RS",
    "republic of sierra leone": "SL",
    "republic of slovenia": "SI",
    "republic of somaliland": "SL",
    "republic of south africa": "ZA",
    "republic of south sudan": "SS",
    "republic of suriname": "SR",
    "republic of tajikistan": "TJ",
    "republic of the congo": "CG",
    "republic of the gambia": "GM",
    "republic of the philippines": "PH",
    "republic of the sudan": "SD",
    "republic of the union of myanmar": "MM",
    "republic of trinidad and tobago": "TT",
    "republic of tunisia": "TN",
    "republic of turkey": "TR",
    "republic of uganda": "UG",
    "republic of uzbekistan": "UZ",
    "republic of vanuatu": "VU",
    "republic of yemen": "YE",
    "republic of zambia": "ZM",
    "republic of zimbabwe": "ZW",
    "rom.": "RO",
    "romania": "RO",
    "rus.": "RU",
    "russia": "RU",
    "russian federation": "RU",
    "rwa.": "RW",
    "rwanda": "RW",
    "s. is.": "SB",
    "s. sud.": "SS",
    "s. sudan": "SS",
    "s.af.": "ZA",
    "s.k.": "KR",
    "s.l.": "SL",
    "sahrawi arab democratic republic": "EH",
    "saud.": "SA",
    "saudi arabia": "SA",
    "sen.": "SN",
    "senegal": "SN",
    "serb.": "RS",
    "serbia": "RS",
    "sierra leone": "SL",
    "slo.": "SI",
    "slovak republic": "SK",
    "slovakia": "SK",
    "slovenia": "SI",
    "socialist republic of vietnam": "VN",
    "solnd.": "SL",
    "solomon is.": "SB",
    "solomon islands": "SB",
    "som.": "SO",
    "somalia": "SO",
    "somaliland": "SL",
    "south africa": "ZA",
    "south korea": "KR",
    "south sudan": "SS",
    "sp.": "ES",
    "spain": "ES",
    "sri l.": "LK",
    "sri lanka": "LK",
    "state of eritrea": "ER",
    "state of israel": "IL",
    "state of kuwait": "KW",
    "state of qatar": "QA",
    "sudan": "SD",
    "sultanate of oman": "OM",
    "sur.": "SR",
    "suriname": "SR",
    "svk.": "SK",
    "swaziland": "SZ",
    "swe.": "SE",
    "sweden": "SE",
    "swiss confederation": "CH",
    "switz.": "CH",
    "switzerland": "CH",
    "syria": "SY",
    "syrian arab republic": "SY",
    "t.l.": "TL",
    "taiwan": "TW",
    "tajikistan": "TJ",
    "tanz.": "TZ",
    "tanzania": "TZ",
    "territory of the french southern and antarctic lands": "TF",
    "thai.": "TH",
    "thailand": "TH",
    "the bahamas": "BS",
    "the congo": "CD",
    "the french southern and antarctic lands": "TF",
    "the gambia": "GM",
    "the netherlands": "NL",
    "the philippines": "PH",
    "the sudan": "SD",
    "the union of myanmar": "MM",
    "timor-leste": "TL",
    "tjk.": "TJ",
    "togo": "TG",
    "togolese republic": "TG",
    "tr.t.": "TT",
    "trinidad and tobago": "TT",
    "tun.": "TN",
    "tunisia": "TN",
    "tur.": "TR",
    "turkey": "TR",
    "turkish republic of northern cyprus": "CN",
    "turkm.": "TM",
    "turkmenistan": "TM",
    "u.a.e.": "AE",
    "u.k.": "GB",
    "u.s.a.": "US",
    "uga.": "UG",
    "uganda": "UG",
    "ukr.": "UA",
    "ukraine": "UA",
    "united arab emirates": "AE",
    "united kingdom": "GB",
    "united kingdom of great britain and northern ireland": "GB",
    "united mexican states": "MX",
    "united republic of tanzania": "TZ",
    "united states": "US",
    "united states of america": "US",
    "uruguay": "UY",
    "ury.": "UY",
    "uzb.": "UZ",
    "uzbekistan": "UZ",
    "van.": "VU",
    "vanuatu": "VU",
    "ven.": "VE",
    "venezuela": "VE",
    "viet.": "VN",
    "vietnam": "VN",
    "w. sah.": "EH",
    "w. sahara": "EH",
    "west bank and gaza": "PS",
    "western sahara": "EH",
    "yem.": "YE",
    "yemen": "YE",
    "zambia": "ZM",
    "zimb.": "ZW",
    "zimbabwe": "ZW",
    "\u010desko": "CZ",
}

